# Generated by Django 4.1.3 on 2023-01-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_jobsapply_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsapply',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
